[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "test"
]
python_files = "*test_*.py"
junit_family = "legacy"

[tool.coverage.run]
command_line = '-m pytest'

[tool.coverage.report]
precision = 2
skip_covered = true
omit=['*test_*']
fail_under = 10
